config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'pages#about'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'

  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]  #To fix the problem of user_path

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user
    validates :title, presence: true, length: {minimum:3, maximum:50}
    validates :description, presence: true, length: {minimum:10, maximum:300}
    validates :user_id, presence: true #wont create articles without a user
end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles
    before_save { self.email = email.downcase} #saves the emails in db in lowercase 
    #case_sensitive -> it does not accept unique name even ignoring uppercase
    validates :username, presence: true, uniqueness: {case_sensitive: false} ,length: {minimum:3, maximum:25}

    VALID_EMAIL_REGEX= /\A\S+@.+\.\S+\z/i
    validates :email, presence: true, length:{maximum:105}, uniqueness:{case_sensitive: false}, format: { with: VALID_EMAIL_REGEX }

    has_secure_password 
    
    include Gravtastic
    gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
        #Checks first if is there already an current user, to not being hiting the db so many times
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
        #converts the obj in true/false, to check if the ir an user or not
        !!current_user 
    end

    def requeire_user
        if !logged_in?
            flash[:danger] = "You must be logged in to do this action"
            redirect_to root_path
        end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    #calls that method only in some other methods
    before_action :set_article, only: [:edit, :update, :show, :destroy]

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        @article.user = User.find(7)

        if @article.save
            flash[:notice]="Article was successfuly created"
            redirect_to article_path(@article)
        else
            render 'new'
        end
    end

    def show
    end

    def edit
    end        
    
    def update
        if @article.update(article_params)
            flash[:notice] = "Article was successfully updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def destroy
        @article.destroy
        flash[:notice]="Article was successfully deleted"
        redirect_to articles_path
    end

    def index #for listing articles
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

private
    def set_article
        @article = Article.find(params[:id])
    end
    
    def article_params
        #shows what was passed in inputs
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            flash[:notice]="Signed up successfuly"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end        
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account was successfully updated"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    private
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    
    end

    def about
    
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
        
    end

    def create
        user = User.find_by_email(params[:session][:email])
        if user && user.authenticate(params[:session][:password])
            session[:user_id] = user.id
            redirect_to user_path(user), notice: "Logged in!"
        else
            flash.now[:alert] = "Email or password is invalid"
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path
    end
    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)

        if @user.save
            flash[:notice]="Signed up successfuly"
            redirect_to articles_path
        else
            render 'new'
        end
    end

    def show
        @user = User.find(params[:id])
        @user_articles  = @user.articles.paginate(page: params[:page], per_page: 5)
    end

    def edit
        @user = User.find(params[:id])
    end        
    
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Your account was successfully updated"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def index 
        @users = User.paginate(page: params[:page], per_page: 5)
    end
    
    private
        def user_params
            params.require(:user).permit(:username, :email, :password)
        end
    
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user)
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
        image_tag(gravatar_url, alt: user.username, class:"img-circle")
        
    end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article|%>
  <div class="row">
     <div class="col-xs-8 col-xs-offset-2">
       <div class="well well-lg">
          <div class="article-title">
           <%=link_to article.title, article_path(article)%>
          </div>
          <div class="article-body">
           <%=truncate(article.description, length:100)%>
           <small>Created by: <%= article.user.username if article.user%></small>
          </div>
          <div class="article-actions">
          <%= link_to 'Edit', edit_article_path(article), class: "btn btn-xs btn-primary"%>
          <%= link_to 'Delete', article_path(article),class:"btn btn-xs btn-danger", method: :delete, data: {confirm:"Are you sure?"}%>
     </div>
   </div>
 </div>
</div>
<%end%>

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
<h2>The following errors prevented the creation of the article</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
        
            <li><%=msg%></li>
        
        <%end%>
    </ul>

<%end%>

<div class="row">
 <div class="col-xs-12">
    <%= form_for(@article, :html=>{class:"form-horizontal", role:"form"}) do |f|%>
     <div class="form-group">
      <label class="col-sm-2 control-label">Title</label>
       <div class="col-sm-8">
        <%= f.text_field :title, class:"form-control",placeholder:"Title of article",autofocus:true %>
       </div> 
      </div>
    <div class="form-group">
      <label class="control-label col-sm-2">Description</label>
        <div class="col-sm-8">
            <%= f.text_area :description, rows:10, class:"form-control", placeholder:"Body of article", autofocus:true %>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">      
            <%=f.submit class:"btn btn-primary btn-lg"%>
        </div>
    </div>
    </div>
 </div>  
    <% end %>

<div class="col-xs-4 col-xs-offset-4">
    <%= link_to 'Cancel request and return to articles listing',articles_path%>
</div>  

app/views/articles/edit.html.erb
<h1 align="center"> Edit an existing article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 align="center">Listing all articles</h1>

<div align="center">
    <%= will_paginate %>
</div>


<%=render 'article', obj: @articles%>

<div align="center">
    <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center"> Create an article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 align="center">Title: <%= @article.title%></h2>
<div "well col-cx-8 col-xs-offset-2">
    <hr>
    <h4><strong>Description:</strong></h4>
    <%= simple_format(@article.description)%>
    <hr>
    <h4><strong>Owner:</strong></h4>
    <%= link_to simple_format(@article.user.username), user_path(@article.user) if @article.user%>
    <%= image_tag @article.user.gravatar_url,size:50, class:"img-circle" %>
    
    <small> 
           Created: <%= time_ago_in_words(@article.created_at) %> ago &nbsp; &nbsp;
           Last update: <%= time_ago_in_words(@article.updated_at)%> ago
    </small>1
    <hr>
    <div class="article-actions">
        <%= link_to 'Edit this article',edit_article_path(@article), class:"btn btn-xs btn-primary"%>
        <%= link_to 'View all articles',articles_path, class:"btn btn-xs btn-success"%>   
        <%= link_to 'Delete this article',articles_path(@article),method: :delete,
        data:{confirm: "Are you sure you want to delete this article? "}, class:"btn btn-xs btn-danger"%>   
    </div>
    </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
    <footer class="footer">
        <small>
        Copyright &copy; <a href="www.google.com"> This is just an example of footer </a> 
        by <a href="www.udemy.com"> Vinicio Rodriguez </a> 
        </small>
        <nav>
            <ul>
                <li><%=link_to "About page", about_path%><li>
            </ul>
        </nav>
    </footer>
</div>

app/views/layouts/_messages.html.erb
  <% flash.each do |name,msg|%>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <%=link_to "Alpha blog", root_path, class: "navbar-brand",id:"logo"%>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "Articles", articles_path%></li>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Actions
        <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a><%=link_to "New Article", new_article_path%></a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    <% if logged_in?%>
      <li><%= link_to 'Log out', logout_path, method: :delete %></li>
      <li><a href="#">Page 3</a></li>
    <% else %>
      <li><%= link_to 'Log in', login_path %></li>
      <li><%= link_to 'Sign up', signup_path%></li>
    <%end%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'layouts/navigation'%>
    <%=render 'layouts/messages'%>
    <div class="container">
      <%= yield %>
    </div>
    <%=render 'layouts/footer'%>
  </body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html> 
<html lang=en>
<head> 
	<meta charset=utf-8>
	<title> Mi primer sitio web </title>
	<link rel="stylesheet" type="text/css" href="css/estilos.css">
</head>

<body>
	
	<header>
		<div>
			<img src="imagenes/patolucas.jpg" width="100" alt="">
		</div>

		<nav>
			<ul>
				<li><a href="<%= root_path %>">Inicio</a></li>  
				<li><a href="">Aplicaciones</a></li>
				<li><a href="">Trabajos</a></li>
				<li><a href="<%= about_path %>">Sobre nosotros</a></li>
			</ul>
		</nav>

	</header>

	<section class="main"> 
		<section class="articles">
			
			<article>
				<h2>Bienvenidos</h2>
				<p>Actualmente en esta sede se imparten las carreras de Ingeniería en Agronomía, Ingeniería en Computación, Administración de Empresas, Ingeniería en Producción Industrial y Gestión en Turismo Rural Sostenible. En el 2013 se da la apertura de la carrera de Ingeniería en Electrónica, la cual es importante para colaborar con el desarrollo tecnológico de la zona.</p>
			</article>

			<article>
				<h2>Segundo articulo</h2>
				<p>a mayor autoridad del Tecnológico es la Asamblea Institucional, que está formada por la representación de docentes, funcionarios y estudiantes, y se divide en la Asamblea Institucional Plebiscitaria y la Asamblea Representativa, y se encarga de políticas generales y ver temas como las reformas al Estatuto Orgánico. Le sigue el Consejo Institucional.</p>

			</article>
		</section>
		<aside>
			<h3>Informacion menos relevante</h3>

			<p>Actualmente, después de ser reelecto en 2015, Calvo sigue como rector del TEC.</p>
		</aside>

		<footer>
		<p>Instituto Tecnologico de Costa Rica - 2018</p>
	    </footer>

	</section>
</body>
</html>

app/views/pages/home.html.erb
  <div class="center jumbotron">
    <h1 id="title">ALPHA BLOG</h1>      
    <%= link_to "Sign Up now", signup_path, class:"btn btn-primary btn-lg"%>
</div>

</body>
</html>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
<h2>The following errors prevented the creation of the article</h2>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
        
            <li><%=msg%></li>
        
        <%end%>
    </ul>

<%end%>

<div class="row">
 <div class="col-xs-12">
    <%= form_for(@user, :html=>{class:"form-horizontal", role:"form"}) do |f|%>
     <div class="form-group">
      <label class="col-sm-2 control-label">Username</label>
       <div class="col-sm-8">
        <%= f.text_field :username, class:"form-control",placeholder:"Enter username",autofocus:true %>
       </div> 
      </div>
    <div class="form-group">
      <label class="control-label col-sm-2">Email</label>
        <div class="col-sm-8">
            <%= f.email_field :email, rows:10, class:"form-control", placeholder:"Enter Email", autofocus:true %>
        </div>
    </div>
    <div class="form-group">
      <label class="control-label col-sm-2">Password</label>
        <div class="col-sm-8">
            <%= f.password_field :password, rows:10, class:"form-control", placeholder:"Enter a password", autofocus:true %>
        </div>
    </div>

    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">      
            <%=f.submit(@user.new_record? ? "Sign Up" : "Update your account", class:"btn btn-primary btn-lg")%>
        </div>
    </div>
    </div>
 </div>  
    <% end %>

<div class="col-xs-4 col-xs-offset-4">
    <%= link_to 'Cancel request and return to articles listing',articles_path%>
</div>  

app/views/users/edit.html.erb
<h1 align="center"> Edit your account </h1>

<%= render 'form'%>

app/views/users/index.html.erb
<h1 align="center"> Alpha Bloggers! </h1>
<div align="center">
    <%= will_paginate %>
</div>
<% @users.each do |user|%>
  <div class="listing">
     <div class="row">
       <div class="well col-md-4 col-md-offset-4">
           
          <%= image_tag user.gravatar_url,size:80, class:"img-circle" %>
           
          <div class="article-title">
           <%=link_to user.username, user_path(user)%>
          </div>
           <small><%= pluralize(user.articles.count,"article") if user.articles%></small>
           
     </div>
 </div>
</div>
<%end%>
<div align="center">
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 align="center"> Sign Up </h1>

<%= render 'form'%>

app/views/users/show.html.erb
<h1 align="center"> Welcome to <%= @user.username%>'s page! </h1>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
    <%= image_tag @user.gravatar_url,size:150, class:"img-circle" %>
    </div>
</div>
<h4 align="center"><%= @user.username%>'s articles!</h4>

<div align="center">
    <%= will_paginate @user_articles %>
</div>

<%= render 'articles/article', obj: @user_articles%>

<div align="center">
    <%= will_paginate @user_articles %>
</div>